# fly.toml app configuration file generated for f1-analyzer on 2026-06-09T08:25:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f1-analyzer'
primary_region = 'ams'

[build]

[env]
  CACHE_DIR = '/data/cache'
  DEBUG = 'false'
  HOST = '0.0.0.0'
  PORT = '8050'

[[mounts]]
  source = 'f1_cache'
  destination = '/data/cache'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 10
    soft_limit = 5

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
